# Generated by Django 4.2.3 on 2023-09-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doct_dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Doctor_id', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Doctor_Department',
            },
        ),
    ]
