# Generated by Django 4.2.3 on 2023-09-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_doct_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='doct_Johnson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(max_length=50)),
                ('Doctor_date', models.CharField(max_length=5)),
                ('cnt', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Doctor_Johnson',
            },
        ),
    ]
