# Generated by Django 4.2.3 on 2023-09-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0003_doct_johnson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doct_johnson',
            name='Doctor_date',
            field=models.IntegerField(max_length=5),
        ),
    ]
