# Generated by Django 4.2.3 on 2023-09-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0004_alter_doct_johnson_doctor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doct_johnson',
            name='Doctor_date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='doct_johnson',
            name='cnt',
            field=models.IntegerField(max_length=50),
        ),
    ]
