# Generated by Django 4.2.3 on 2023-09-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0005_alter_doct_johnson_doctor_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doct_johnson',
            name='Doctor_date',
            field=models.CharField(max_length=50),
        ),
    ]
