# Generated by Django 4.2.3 on 2023-09-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0010_doct_hopkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Bed_Details_List',
            },
        ),
    ]
