# Generated by Django 4.2.3 on 2023-09-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0011_bed_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_details',
            name='bed_Number',
            field=models.CharField(default='101', max_length=50),
            preserve_default=False,
        ),
    ]
