# Generated by Django 4.2.3 on 2023-09-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0013_bed_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed_Confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('ContactNo', models.CharField(max_length=50)),
                ('Comments', models.CharField(max_length=50)),
            ],
        ),
    ]
