# Generated by Django 4.2.3 on 2023-09-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0014_bed_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_apply',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bed_confirm',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
