# Generated by Django 4.2.3 on 2023-09-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0015_bed_apply_is_approved_bed_confirm_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_apply',
            name='BedNo',
            field=models.IntegerField(default=0, max_length=123),
        ),
    ]
