# Generated by Django 4.2.3 on 2023-10-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0016_bed_apply_bedno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed_apply',
            name='is_approved',
            field=models.CharField(max_length=50),
        ),
    ]
