# Generated by Django 4.2.3 on 2023-10-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0017_alter_bed_apply_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed_apply',
            name='is_approved',
            field=models.CharField(default='Vacant', max_length=50),
        ),
    ]
