# Generated by Django 4.2.3 on 2023-10-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0018_alter_bed_apply_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed_confirm',
            name='is_approved',
        ),
    ]
