from django.urls import path
from . import views
urlpatterns=[
    path('',views.index),
    path('home',views.home),
    path('register',views.register),
    path('signin',views.signin),
    path('orthodoc',views.orthodoc),
    path('outdoor',views.outdoor),
    path('paedidoc',views.paedidoc),
    path('cardiodoc',views.cardiodoc),
    path('gynaedoc',views.gynaedoc),
    path('entdoc',views.entdoc),
    path('slotbooksucc',views.slotbooksucc),
    path('reg_store',views.reg_store),
    path('show',views.show),
    path('check',views.check),
     path('access',views.access),
     path('slot_johnson',views.slot_johnson),
     path('slot_jenny',views.slot_jenny),
     path('slot_smith',views.slot_smith),
     path('slot_david',views.slot_david),
     path('slot_hopkin',views.slot_hopkin),
    path('bed_details',views.bed_details),
    path('bed_apply',views.bed_apply),
    path('submit_bed_application',views.submit_bed_application),
    path('bedbookappdone',views.bedbookappdone),
     path('showbedapp',views.showbedapp),
     path('approve/<int:id>/<str:name>/<str:comm>/<str:contact>/',views.approve),
     path('discharge/<int:id>',views.discharge),
      path('bedbooksucc',views.bedbooksucc),
     path('dissucc',views.dissucc),
      path('bed_discharge',views.bed_discharge),
]

