# Generated by Django 3.2.20 on 2023-09-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('E_mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Date_of_Birth', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
