# Generated by Django 3.2.20 on 2023-09-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pleasetablebanao',
            fields=[
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('E_mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Date_of_Birth', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
